class Constant:
    NOME_COGNOME = r"\bLeonardo Caruso\b|\bLeonardo\b|\bCaruso\b"
    EMAIL = r"\bleonardo.caruso@gmail.com\b"
    GENDER = r"\bgender\b"
    ALTEZZA = ""
    PESO = r"\bweight\b"
    BIRTHDATE = r"\bbirthdate\b"
    CELLULARE = r"\b3518842044\b"
    ALTAVILLA = r"Altavilla"
    MATTINE = r"\bMattine\b"
    POSTAL_CODE = r"\b8404\\d\b"
    CARRIER = r"\bVodafone\b"
    PHONE_NAME = r"\bEmmanuel\b"
    UDID = r"\b9c93c5bd4ae0d361640428bd3800f5b588de1699\b"